using System.Collections.Generic;
using Anaglyfin.Profiles;

namespace Anaglyfin.Ffmpeg;

/// <summary>
/// The set of FFmpeg arguments one profile contributes to a transcode command.
/// </summary>
/// <remarks>
/// <para>
/// A rewrite is inert data produced by
/// <see cref="IFfmpegProfileArgumentBuilder"/>: the caller (the FFmpeg wrapper in
/// production, a collector in tests) splices <see cref="InsertArguments"/> into the
/// command it is assembling. Every string in it is generated by the builder from an
/// allowlisted profile id and validated parameters, so nothing in a rewrite can
/// carry a filter, path or colour the builder did not produce itself.
/// </para>
/// <para>
/// Each profile is served by exactly one decode: either the decoder's default base
/// view (plain 2D, which needs no insertion at all) or the all-view native
/// side-by-side pivot that every stereo profile shares. The properties below describe
/// that choice so callers can reason about the rewrite without parsing the argument
/// list.
/// </para>
/// </remarks>
public sealed record ProfileRewrite
{
    /// <summary>
    /// Gets the allowlisted profile id this rewrite was built for.
    /// </summary>
    public required string ProfileId { get; init; }

    /// <summary>
    /// Gets the conversion family of the profile.
    /// </summary>
    public required ProfileKind Kind { get; init; }

    /// <summary>
    /// Gets the complete, ordered FFmpeg arguments to insert into the command.
    /// </summary>
    /// <remarks>
    /// This is the authoritative output: view selection map, video filter chain or
    /// filter graph, output map and subtitle burn-in, already merged the way a single
    /// FFmpeg invocation needs. It is empty for the plain 2D profile, whose output is
    /// what the FFmpeg-mvc binary produces without any Anaglyfin insertion.
    /// </remarks>
    public required IReadOnlyList<string> InsertArguments { get; init; }

    /// <summary>
    /// Gets the video map value the profile requires, if any.
    /// </summary>
    /// <remarks>
    /// <c>0:v:view:all</c> for every stereo profile derived from the all-view pivot,
    /// the output label of the custom filter graph for the custom grayscale profile,
    /// and null for the plain 2D profile, which keeps the decoder's default base view
    /// and the caller's own video map.
    /// </remarks>
    public string? VideoMap { get; init; }

    /// <summary>
    /// Gets the profile conversion video filter chain, without the subtitle burn-in.
    /// </summary>
    /// <remarks>
    /// Null when the profile needs no conversion filter (2D, full SBS) or converts
    /// through <see cref="FilterComplex"/> instead (custom grayscale). Kept separate
    /// from <see cref="InsertArguments"/> so a caller can see the conversion itself
    /// apart from the subtitle stage appended after it.
    /// </remarks>
    public string? VideoFilter { get; init; }

    /// <summary>
    /// Gets the filter graph for profiles that need one, otherwise null.
    /// </summary>
    /// <remarks>
    /// Only the custom grayscale anaglyph uses a graph, because splitting the native
    /// side-by-side frame into two tinted eyes and recombining them cannot be spelled
    /// as a single linear chain. It always starts from the all-view input label, so
    /// the graph still costs exactly one decode.
    /// </remarks>
    public string? FilterComplex { get; init; }

    /// <summary>
    /// Gets the generated subtitle burn-in filter, or null when none was requested.
    /// </summary>
    /// <remarks>
    /// A <c>subtitles</c> filter whose filename is the escaped plugin-provided source
    /// path and whose <c>si</c> is the validated track ordinal.
    /// </remarks>
    public string? SubtitleFilter { get; init; }

    /// <summary>
    /// Gets a value indicating whether subtitle streams must be suppressed on the
    /// rewritten command.
    /// </summary>
    /// <remarks>
    /// True for every profile the rewrite converts: subtitles then reach the picture
    /// exclusively through <see cref="SubtitleFilter"/>, after the stereo conversion,
    /// so mapped or codec-level subtitle streams would double-render text. False for
    /// the plain 2D profile, whose subtitle handling is left to the stock pipeline.
    /// </remarks>
    public bool ShouldSuppressSubtitleStreams { get; init; }

    /// <summary>
    /// Gets a value indicating whether the subtitle burn-in was appended to the
    /// profile conversion filter chain instead of standing alone.
    /// </summary>
    /// <remarks>
    /// True when both a profile <see cref="VideoFilter"/> and a
    /// <see cref="SubtitleFilter"/> exist and <see cref="InsertArguments"/> carries one
    /// combined <c>-vf</c> chain with the burn-in last. False for the custom grayscale
    /// profile (its burn-in is a separate stage applied to the mapped graph output) and
    /// whenever no burn-in was requested.
    /// </remarks>
    public bool ShouldAppendSubtitlesToProfileFilter { get; init; }

    /// <inheritdoc />
    public override string ToString()
        => $"{ProfileId}: {string.Join(' ', InsertArguments)}";
}
