using System.Collections.Generic;
using Anaglyfin.Profiles;

namespace Anaglyfin.Ffmpeg;

/// <summary>
/// The set of FFmpeg arguments one profile contributes to a transcode command.
/// </summary>
/// <remarks>
/// <para>
/// A rewrite is inert data produced by
/// <see cref="IFfmpegProfileArgumentBuilder"/>: the caller (the FFmpeg wrapper in
/// production, a collector in tests) splices it into the command it is assembling. Every
/// string in it is generated by the builder from an allowlisted profile id and validated
/// parameters, so nothing in a rewrite can carry a filter, path or colour the builder did
/// not produce itself.
/// </para>
/// <para>
/// A rewrite is written on both sides of the input it converts, and the two halves are
/// deliberately kept apart because FFmpeg reads them at different moments.
/// <see cref="RequiresComposedViewInput"/> says that the decode itself has to be asked for
/// the composed all-view picture, which is an option on the input: the caller puts
/// <see cref="FfmpegProfileArgumentBuilder.ComposedViewInputOption"/> with the value
/// <see cref="FfmpegProfileArgumentBuilder.ComposedViewInputValue"/> immediately before the
/// <c>-i</c> of the input it converts.
/// <see cref="InsertArguments"/> is the rest: output-side arguments, which the caller puts
/// after its last input. Only the decoder can compose the eyes, so nothing in the output
/// half ever names a view - and FFmpeg refuses a view specifier on a decode that was
/// configured through <c>-view_ids</c> in the first place.
/// </para>
/// <para>
/// The two flags below are the rewrite's shape, stated rather than inferred: a caller that
/// needs to know whether a profile owns the output's video pipeline, or whether it has to
/// be given the composed picture, reads a flag instead of guessing from the presence of a
/// map. Full SBS is the profile that shows why the two are different questions - it owns
/// the pipeline, converts nothing and maps nothing of its own, and is still the profile
/// that cannot run without the composed decode.
/// </para>
/// </remarks>
public sealed record ProfileRewrite
{
    /// <summary>
    /// Gets the allowlisted profile id this rewrite was built for.
    /// </summary>
    public required string ProfileId { get; init; }

    /// <summary>
    /// Gets the conversion family of the profile.
    /// </summary>
    public required ProfileKind Kind { get; init; }

    /// <summary>
    /// Gets the complete, ordered FFmpeg arguments to insert into the output segment of
    /// the command, after its last input.
    /// </summary>
    /// <remarks>
    /// This is the authoritative output-side half: the profile's filter chain, or its
    /// filter graph together with the map of its labelled output, already merged the way a
    /// single FFmpeg invocation needs. It carries no view selection and no view specifier -
    /// the composed picture is an input-time question (<see cref="RequiresComposedViewInput"/>) -
    /// and it is empty for both plain 2D, which is what an unmodified FFmpeg-mvc run
    /// produces anyway, and full SBS, whose conversion is the composed decode itself.
    /// </remarks>
    public required IReadOnlyList<string> InsertArguments { get; init; }

    /// <summary>
    /// Gets a value indicating whether the profile converts the picture at all, and
    /// therefore has to own the output's video pipeline.
    /// </summary>
    /// <remarks>
    /// <para>
    /// True for every profile but plain 2D. It is what entitles a profile to insist: a
    /// command that copies its video has decided that nothing is converted onto this
    /// output, and a command carrying somebody else's filtergraph cannot share the video
    /// pipeline with the profile's filters or graph. Both are refused rather than run, and
    /// the flag is what the caller checks.
    /// </para>
    /// <para>
    /// Owning the pipeline is not the same as owning the output's video <em>map</em>: see
    /// <see cref="VideoMap"/>. Full SBS owns the pipeline while mapping nothing of its own,
    /// because for that profile the composed decode <em>is</em> the output.
    /// </para>
    /// </remarks>
    public bool OwnsVideoPipeline { get; init; }

    /// <summary>
    /// Gets a value indicating whether the profile needs the composed all-view picture
    /// from the decode.
    /// </summary>
    /// <remarks>
    /// <para>
    /// True for every profile but plain 2D, which is served by the decoder's default base
    /// view and must not be given anything else. A caller honouring this flag puts
    /// <c>-view_ids -1</c> immediately before the <c>-i</c> of the input being converted;
    /// asking at open time is what makes the composed route the reliable one, since a view
    /// specifier is only resolved once the decoder has reported its view list, while the
    /// option is already in the decoder's context when decoding starts.
    /// </para>
    /// <para>
    /// The flag comes with a consequence for the rest of the command: a decode configured
    /// through <c>-view_ids</c> refuses a view specifier anywhere else on that input, so a
    /// caller that sets it must also make sure no <c>0:v:view:&#42;</c> map or
    /// <c>[0:v:view:&#42;]</c> filter label survives - which is also why no rewrite this
    /// builder produces ever writes one.
    /// </para>
    /// </remarks>
    public bool RequiresComposedViewInput { get; init; }

    /// <summary>
    /// Gets the video map value the profile maps for itself, otherwise null.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Null for every profile but the custom grayscale anaglyph. A composed decode delivers
    /// its all-view frames on the very stream the server already named, so a linear profile
    /// converting that picture keeps the server's video map and needs none of its own; full
    /// SBS goes further and needs no filter either. The custom profile is the exception
    /// because it does not convert in place: it routes the stream through its own
    /// <see cref="FilterComplex"/> and the labelled graph output is a new stream, which the
    /// command has to name explicitly and which then competes with the server's own video
    /// maps.
    /// </para>
    /// <para>
    /// A caller uses this to decide what may be taken away: a profile with a map of its own
    /// removes the video maps that would compete with it, and a profile without one leaves
    /// the server's stream selection alone.
    /// </para>
    /// </remarks>
    public string? VideoMap { get; init; }

    /// <summary>
    /// Gets the profile conversion video filter chain, without the subtitle burn-in.
    /// </summary>
    /// <remarks>
    /// Null when the profile needs no conversion filter (2D, full SBS) or converts
    /// through <see cref="FilterComplex"/> instead (custom grayscale). Kept separate
    /// from <see cref="InsertArguments"/> so a caller can see the conversion itself
    /// apart from the subtitle stage appended after it.
    /// </remarks>
    public string? VideoFilter { get; init; }

    /// <summary>
    /// Gets the filter graph for profiles that need one, otherwise null.
    /// </summary>
    /// <remarks>
    /// Only the custom grayscale anaglyph uses a graph, because splitting the composed
    /// frame into two tinted eyes and recombining them cannot be spelled as a single linear
    /// chain. It reads the marker input's video stream by index - the stream the composed
    /// decode delivers - and never a view specifier, so the graph still costs exactly one
    /// decode and still obeys the <c>-view_ids</c> contract.
    /// </remarks>
    public string? FilterComplex { get; init; }

    /// <summary>
    /// Gets the filtergraph input label <see cref="FilterComplex"/> reads its source from,
    /// otherwise null.
    /// </summary>
    /// <remarks>
    /// <c>[0:&lt;index&gt;]</c> for the video stream the marker named, or <c>[0:v]</c> when
    /// the marker named none. Exposed next to the graph so a caller can see which stream the
    /// profile reads without parsing the graph text itself.
    /// </remarks>
    public string? FilterComplexInput { get; init; }

    /// <summary>
    /// Gets the generated subtitle burn-in filter, or null when none was requested.
    /// </summary>
    /// <remarks>
    /// A <c>subtitles</c> filter whose filename is the escaped plugin-provided source
    /// path and whose <c>si</c> is the validated track ordinal.
    /// </remarks>
    public string? SubtitleFilter { get; init; }

    /// <summary>
    /// Gets a value indicating whether subtitle streams must be suppressed on the
    /// rewritten command.
    /// </summary>
    /// <remarks>
    /// True exactly where <see cref="SubtitleFilter"/> was built: the text of this file is then
    /// rendered onto the picture by this rewrite, and a mapped or codec-level subtitle stream
    /// beside it would double-render it. Converting a picture says nothing about the text on it,
    /// so every other rewrite leaves the caller's subtitle choice alone - its maps, and the
    /// subtitle streams its own filter graphs read - exactly as the plain 2D profile always did.
    /// </remarks>
    public bool ShouldSuppressSubtitleStreams { get; init; }

    /// <summary>
    /// Gets a value indicating whether the subtitle burn-in was appended to the
    /// profile conversion filter chain instead of standing alone.
    /// </summary>
    /// <remarks>
    /// True when both a profile <see cref="VideoFilter"/> and a
    /// <see cref="SubtitleFilter"/> exist and <see cref="InsertArguments"/> carries one
    /// combined <c>-vf</c> chain with the burn-in last. False for the custom grayscale
    /// profile (its burn-in is a separate stage applied to the mapped graph output) and
    /// whenever no burn-in was requested.
    /// </remarks>
    public bool ShouldAppendSubtitlesToProfileFilter { get; init; }

    /// <inheritdoc />
    public override string ToString()
        => $"{ProfileId}: {string.Join(' ', InsertArguments)}";
}
